require: 
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false